### ISSUE TITLE
Implementation of loss function

### ISSUE THREAD

**Issue by LiuYuLOL** [nju-websoft/AliNet#3]
Hi thanks for the great work.

I'm just reading the code and wondering where is the implementation of the L loss (equation 11 in the paper)?

Cheers,
Yu

**Comment by sunzequn** [comment]
Hi Yu,

Thanks for your interest in our work! The overall loss is implemented at [line 330 of the alinet.py](https://github.com/nju-websoft/AliNet/blob/48f2d20e87da28853f99bf6e60fe73e1c0ab3ea6/code/alinet.py#L330).

**Comment by LiuYuLOL** [comment]
Thanks for your reply.

Sorry. I got an old version file. Just notice the update.

Can I ask why ''r_x + r_y'' can be regarded as the new relation when generate_2hop_triples?

**Comment by sunzequn** [comment]
It has no meaning, just the placeholder to form triple-like edges used for the adjacent matrix generation, where the edge types (i.e., relations) do not count.

**Comment by LiuYuLOL** [comment]
Thanks!
